### ISSUE TITLE
Tidal-DL_x64.exe: Can't download

### ISSUE THREAD

**Issue by Sapphireinc** [Sorrow446/Ti-DL#2]
Traceback (most recent call last):
  File "Tidal-DL.py", line 536, in <module>
  File "pathlib.py", line 1226, in mkdir
  File "pathlib.py", line 387, in wrapped
NotADirectoryError: [WinError 267] Nom de répertoire non valide: 'Tidal-DL Downloads\\Various Artists - Function Underground: The Black and Brown American Rock Sound 1969-1974'
[9336] Failed to execute script Tidal-DL

**Comment by Sorrow446** [comment]
String replace regex isn't replacing colons like it should be. I'll do further testing to see if it's not replacing more characters it should be.

**Comment by Sorrow446** [comment]
Fixed in release 1d.
