### ISSUE TITLE
[5670] Failed to execute script Tidal-DL

### ISSUE THREAD

**Issue by xRock60** [Sorrow446/Ti-DL#7]
Hello,
with that : https://listen.tidal.com/album/108615852

I get that : 
Downloading track 2 of 12: Lufthansa - 320 kbps AAC  100%
Traceback (most recent call last):
  File "Tidal-DL.py", line 762, in <module>
  File "Tidal-DL.py", line 681, in rip
  File "Tidal-DL.py", line 538, in add_flac_tags
  File "site-packages\mutagen\_file.py", line 49, in __init__
  File "site-packages\mutagen\_util.py", line 169, in wrapper
  File "site-packages\mutagen\_util.py", line 140, in wrapper
  File "site-packages\mutagen\flac.py", line 789, in load
  File "site-packages\mutagen\flac.py", line 911, in __check_header
mutagen.flac.FLACNoHeaderError: '2.flac' is not a valid FLAC file
[5760] Failed to execute script Tidal-DL

**Comment by Sorrow446** [comment]
Hello. This should be a simple fix. I'll get to work later on today.

**Comment by Sorrow446** [comment]
Please try [this](https://thoas.feralhosting.com/sorrow/Tidal-DL/Ti-DL_r1e_experimental/Ti-DL_x86.exe) experimental build. Linux build may come later on today too.

**Comment by xRock60** [comment]
Hello
Working with this build!

**Comment by Sorrow446** [comment]
Great! :) Will roll out a new build soon.
